export enum ENUM_ACTOR_STATUS_CODE_ERROR {
    ACTOR_IS_INACTIVE_ERROR = 5800,
    ACTOR_NOT_FOUND_ERROR = 5801,
    ACTOR_EXIST_ERROR = 5802,
    ACTOR_ACTIVE_ERROR = 5803,
    ACTOR_USED_ERROR = 5804,
}
